// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJau8VaMwk7fAMczRxEXCRIykPDUpq0Mk',
    appId: '1:189013248969:web:29e61431187b2a92227618',
    messagingSenderId: '189013248969',
    projectId: 'facebookclone-23tech',
    authDomain: 'facebookclone-23tech.firebaseapp.com',
    storageBucket: 'facebookclone-23tech.appspot.com',
    measurementId: 'G-KYHSYEL73V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0uHu3hdBN4cGm6oZGWXQVvZzRUj8tjeQ',
    appId: '1:189013248969:android:7d1d415cd49d4b27227618',
    messagingSenderId: '189013248969',
    projectId: 'facebookclone-23tech',
    storageBucket: 'facebookclone-23tech.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8p5rqo3yIPes4FtV2xGtvHcjRL5TNjtw',
    appId: '1:189013248969:ios:e32b7a7b0c75ca00227618',
    messagingSenderId: '189013248969',
    projectId: 'facebookclone-23tech',
    storageBucket: 'facebookclone-23tech.appspot.com',
    iosBundleId: 'com.example.flutterNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8p5rqo3yIPes4FtV2xGtvHcjRL5TNjtw',
    appId: '1:189013248969:ios:e32b7a7b0c75ca00227618',
    messagingSenderId: '189013248969',
    projectId: 'facebookclone-23tech',
    storageBucket: 'facebookclone-23tech.appspot.com',
    iosBundleId: 'com.example.flutterNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJau8VaMwk7fAMczRxEXCRIykPDUpq0Mk',
    appId: '1:189013248969:web:c196f1fa8aa09c9c227618',
    messagingSenderId: '189013248969',
    projectId: 'facebookclone-23tech',
    authDomain: 'facebookclone-23tech.firebaseapp.com',
    storageBucket: 'facebookclone-23tech.appspot.com',
    measurementId: 'G-8L1T3LV2L9',
  );
}
